<?php

/**
 * @file
 * Primary module hooks for KLOG - Blog article module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;

function klog_blog_entity_extra_field_info() {
  $extra = [];

  $extra['node']['blog_article']['display']['estimated_read_time'] = [
    'label' => t('Estimated read time'),
    'weight' => 100,
    'visible' => FALSE,
  ];


    $extra['node']['blog_article']['display']['previous_next_article'] = [
      'label' => t('Buttons to previous and next blog article '),
      'weight' => 100,
      'visible' => FALSE,
    ];



  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function klog_blog_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  $bem_block = Html::getClass( 'node-' . $node->bundle() . ($view_mode == 'default' ? '' : '-' . $view_mode));
  if ($display->getComponent('estimated_read_time')) {
    $node_paragraphs = $node->get('field_paragraphs')->referencedEntities();
    $estimated_read_time = _klog_blog_estimated_read_time($node_paragraphs);
    $build['estimated_read_time'] = [
      '#type' => 'inline_template',
      '#template' => '<div class="{{ bem_block }}__estimated-read-time">{{ estimated_read_time }} min.</div>',
      '#context' => [
        'bem_block' => $bem_block,
        'estimated_read_time' => $estimated_read_time,
    ]
    ];
  }

  if ($display->getComponent('previous_next_article')) {
    $build['previous_next_article'] = [
      '#theme' => 'klog_previous_next__blog_article',
      '#entity' => $node,
    ];
  }
}

/**
 * Calculates estimated read time for article.
 *
 * @param \Drupal\paragraphs\ParagraphInterface[] $paragraphs
 *   An array with paragraphs.
 * @return float
 *   The estimated read time in minutes.
 */
function _klog_blog_estimated_read_time(array $paragraphs) {
  $word_per_minute = 143;
  $estimated_read_time = 0;

  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  foreach ($paragraphs as $paragraph) {
    switch ($paragraph->bundle()) {
      case 'text':
        $body_value = $paragraph->get('field_body')->value;

        // Видалення HTML-тегів.
        $stripped_text = strip_tags($body_value);

        // Видалення всіх символів крім букв (включаючи кирилицю) і цифр.
        $cleaned_text = preg_replace('/[^\p{L}\p{N}\s]/u', '', $stripped_text);

        // Підрахунок слів.
        $word_count = preg_match_all('/\p{L}+/u', $stripped_text);

        $estimated_read_time += floor(($word_count / $word_per_minute) * 60);
        break;

      case 'gallery':
        $estimated_read_time += 30;
        break;

      case 'image':
        $estimated_read_time += 10;
        break;

      case 'code':
        $body_value = $paragraph->get('field_body')->value;

        // Видалення HTML-тегів.
        $stripped_text = strip_tags($body_value);

        // Видалення всіх символів крім букв (включаючи кирилицю) і цифр.
        $cleaned_text = preg_replace('/[^\p{L}\p{N}\s]/u', '', $stripped_text);

        // Підрахунок слів.
        $word_count = preg_match_all('/\p{L}+/u', $stripped_text);


        $estimated_read_time += floor(($word_count / $word_per_minute / 3) * 60);
        break;
    }
  }

  return ceil($estimated_read_time / 60) >= 1 ?: 1;
}
