<?php

/**
 * @file
 * Main file for custom hooks and function
 */

/**
 * Implements hook_theme().
 */
function klog_hero_theme($existing, $type, $theme, $path) {
  return [
    'klog_hero' => [
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'image' => NULL,
        'video' => [],
      ],
      'file' => 'klog_hero.theme.inc',
      'pattern' => 'klog_hero__',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK() for klog-hero.html.twig.
 */
function klog_hero_suggestions_klog_hero(array $variables) {
  $suggestions = [];

  if(!empty($variables['image'])) {
    $suggestions[] = 'klog_hero__image';
  }

  if(!empty($variables['image'] && !empty($variables['video']))) {
    $suggestions[] = 'klog_hero__video';
  }

  return $suggestions;
}
