<?php

/**
 * @file
 * Main file for custom hooks and functions
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\imagemagick\ImagemagickExecArguments;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme
 */
function klog_theme ($existing, $type, $path) {
  return [
    'klog_previous_next' => [
      'variables' => [
        'entity' => NULL,
      ],
      'file' => 'klog.theme.inc',
      'pattern' => 'klog_previous_next__',
    ],
    'klog_label_with_icon_media_formatter' => [
      'variables' => [
        'url' => NULL,
        'label' => NULL,
        'filesize' => NULL,
        'media_type' => NULL,
        'mime_type' => NULL,
      ],
      'file' => 'klog.theme.inc',
    ]
  ];
}


/**
 * Implements hook_imagemagick_arguments_alter().
 */
function klog_imagemagick_arguments_alter(ImagemagickExecArguments $arguments, $command) {
  $arguments->add('-sampling-factor 4:2:0');
  $arguments->add('-interlace Plane');
  $arguments->add('-strip');
}
